# Numpy Array

In [1]:
import numpy as np
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [2]:
#Upcasting:

In [3]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [4]:
#two dimensions

In [5]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [6]:
#Minimum dimensions 2:

In [7]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [8]:
#dtype

In [9]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
#Data-type consisting of more than one element:

In [11]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [12]:
type(x[1][0])

numpy.int16

In [13]:

#Creating an array from sub-classes:

In [14]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [15]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [16]:
np.mat('1 2;3 4;5 6')

matrix([[1, 2],
        [3, 4],
        [5, 6]])

# numpy.asarray

In [17]:
#Convert the input to an array.

In [18]:
#Convert a list into an array:

In [19]:
 a = [1, 2]
type(a)

list

In [20]:
type(np.asarray(a))

numpy.ndarray

In [21]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [22]:
a = [1,4,9]
b= np.array(a)
type(b)

z = np.asarray(a)
type(z)



numpy.ndarray

In [23]:
np.asarray((1,2))

array([1, 2])

In [24]:
#If dtype is set, array is copied only if dtype does not match:

In [25]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [26]:
np.asarray([1,2],dtype=np.float32) is a

False

In [27]:
np.asarray([1,2])

array([1, 2])

In [28]:
np.asarray(a, dtype=np.float64) is a

False

In [29]:
# ndarray subclasses are not passed through

In [30]:
issubclass(np.matrix, np.ndarray)

True

In [31]:
a = np.matrix([[1, 2]])
np.asanyarray(a)


matrix([[1, 2]])

In [32]:
np.asarray(a) is a

False

In [33]:
np.asanyarray(a) is a

True

In [34]:
type(np.asarray(a))

numpy.ndarray

# numpy.asanyarray

In [35]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [36]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [37]:
np.asanyarray([1,2]) is a

False

In [38]:
np.array(a, copy=True)  

array([[1, 2]])

In [39]:
#Create an array x, with a reference y and a copy z:

In [40]:
x = np.array([1, 2, 3])
x
y

NameError: name 'y' is not defined

In [ ]:
y = x

In [ ]:
z = np.copy(x)

In [ ]:
y[0] = 100
x

In [ ]:
x

In [ ]:
id(x[0])

In [ ]:
id(y[0])

In [ ]:
id(x) 

In [ ]:
id(y)

# numpy.fromfunction

In [ ]:
#Construct an array by executing a function over each coordinate.

In [ ]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

In [ ]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

In [ ]:
#Create a new 1-dimensional array from an iterable object.

In [ ]:
iterable = (x*x for x in range(5))
iterable

In [ ]:
np.fromiter(iterable, float)

In [ ]:
#A new 1-D array initialized from text data in a string

In [ ]:
a = np.fromstring('234 234',sep=' ')
a

In [ ]:
np.fromstring('1, 2', dtype=int, sep=',')

In [ ]:
# How to create create a record array from a (flat) list of arrays

In [ ]:
x1=np.array([1,2,3,4])

In [ ]:
x2=np.array(['a','dd','xyz','12'])

In [ ]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

In [ ]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

In [ ]:
print(r[1]["a"])

In [ ]:
x1[1]

# data types

In [ ]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


In [ ]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


In [ ]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

# arange and linspace

In [ ]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

In [ ]:
list(range(5,16,2))

In [ ]:
list(range(50,-1,5))

In [ ]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

In [ ]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

In [ ]:
print("Every 5th number from 50 in reverse order\n",np.arange(20.0,-1,-5))

In [ ]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

# Matrix creation

In [ ]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

In [ ]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

In [ ]:
print("Vector of ones\n---------------------")
print(np.ones(5))

In [ ]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


In [ ]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

In [ ]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

In [ ]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

In [ ]:
np.arange(4)

In [ ]:
np.arange(3.0)

In [ ]:
 np.arange(3,7)

In [ ]:
np.arange(3,7,2)

In [ ]:
np.linspace(2.0, 3.0, num=5)

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

In [ ]:
np.linspace(2.0, 3.0, num=9, retstep=True)

In [ ]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

In [ ]:
np.logspace(2.0, 3.0, num=4,base = 10)

In [ ]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

In [ ]:
np.logspace(2.0, 3.0, num=4, base=2.0)

In [ ]:
#Extract a diagonal or construct a diagonal array.

In [ ]:
x = np.arange(16).reshape((-1,4))

In [ ]:
x

In [ ]:
np.diag(x)

In [ ]:
np.diag(x, k=2
       )

In [ ]:
np.diag(x, k=-1)

In [ ]:
np.diag(np.diag(x))

In [ ]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [ ]:
np.diagflat([[1,2], [3,4]])

In [ ]:
np.diagflat([1,2], 1)

In [ ]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [ ]:
np.tri(3, 5, 1, dtype=int)

In [ ]:
np.tri(3, 5,k=-1)

In [ ]:
#return a Lower triangle of an array.

In [ ]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

In [ ]:
#return Upper triangle of an array.

In [ ]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

# Random number generation

In [ ]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

In [ ]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

In [ ]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


In [ ]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

# Reshaping

In [45]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c


array([[98,  8,  9, 92, 82],
       [79, 17, 49, 28,  1],
       [59, 65, 85, 86, 86],
       [74, 27,  8, 40, 25],
       [97, 56, 18, 73, 91],
       [41, 21, 18,  2, 67]])

In [ ]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


In [ ]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


In [ ]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


In [ ]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M

In [ ]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

In [ ]:
M

In [ ]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

# Indexing and slicing

In [ ]:
arr = np.arange(0,11)
print("Array:",arr)


In [ ]:
print("Element at 7th index is:", arr[7])


In [ ]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


In [ ]:
print("Elements up to 4th index are:", arr[:4])
arr

In [ ]:
print("Elements from last backwards are:", arr[-1:7:-1])


In [ ]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


In [41]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [42]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [46]:
import numpy as np
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[10 20 60 23 69]
 [81 63 40 35 62]
 [53 99 48 16 83]]


array([[20, 23],
       [63, 35],
       [99, 16]])

In [53]:
mat = np.array(ri(10,100,15)).reshape(3,5)
mat

array([[73, 85, 88, 76, 57],
       [30, 83, 82, 74, 66],
       [60, 79, 91, 98, 69]])

In [57]:
mat[1:4,3:5]

array([[74, 66],
       [98, 69]])

In [ ]:
mat[0:3,[1,3]]
mat

In [ ]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat

In [ ]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")


In [ ]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


In [ ]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])


In [ ]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

# Subseting

In [58]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[23 17 98 67 33]
 [32 51 55 74 80]
 [80 73 77 18 23]]


array([[False, False,  True,  True, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True, False, False]])

In [59]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [98 67 51 55 74 80 80 73 77]


# Slicing

In [62]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [67]:
mat[:2,:2]

array([[11, 12],
       [21, 22]])

In [64]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")
mat_slice


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


array([[11, 12],
       [21, 22]])

In [68]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [69]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [70]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [71]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [72]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [73]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [74]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[3 7 3]
 [9 3 3]
 [1 9 9]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[4 7 8]
 [3 5 7]
 [5 3 3]]


In [75]:
mat1*mat2

array([[12, 49, 24],
       [27, 15, 21],
       [ 5, 27, 27]])

In [76]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[ 48  65  82]
 [ 60  87 102]
 [ 76  79  98]]


In [77]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\Users\Home\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [78]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[103 107 103]
 [109 103 103]
 [101 109 109]]


In [79]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[ 27 343  27]
 [729  27  27]
 [  1 729 729]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[ 27 343  27]
 [729  27  27]
 [  1 729 729]]


# Broadcasting

In [ ]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [80]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [81]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [82]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [83]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [84]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [85]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [86]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[7 2 4]
 [1 1 6]
 [7 7 8]]

2nd Matrix of random single-digit numbers
------------
 [[7 8 9]
 [5 5 8]
 [8 3 2]]


In [87]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[2.64575131 1.41421356 2.        ]
 [1.         1.         2.44948974]
 [2.64575131 2.64575131 2.82842712]]


In [88]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.09663316e+03 7.38905610e+00 5.45981500e+01]
 [2.71828183e+00 2.71828183e+00 4.03428793e+02]
 [1.09663316e+03 1.09663316e+03 2.98095799e+03]]


In [89]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.84509804 0.30103    0.60205999]
 [0.         0.         0.77815125]
 [0.84509804 0.84509804 0.90308999]]
[[7 2 4]
 [1 1 6]
 [7 7 8]]
[[7 8 9]
 [5 5 8]
 [8 3 2]]


In [90]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[0 2 4]
 [1 1 6]
 [7 1 0]]


array([[0, 2, 4],
       [1, 1, 6],
       [7, 1, 0]], dtype=int32)

In [91]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [92]:
A = np.linspace(0,12*np.pi,1001)


In [93]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])

In [95]:
matt = np.arange(2,14).reshape(3,4)

In [96]:
matt

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [97]:
doub = pow(matt,2)

In [98]:
doub

array([[  4,   9,  16,  25],
       [ 36,  49,  64,  81],
       [100, 121, 144, 169]], dtype=int32)

In [99]:
import numpy as np
x=np.array([1,2,3,4,5]) 
N=5 
matrix = np.column_stack([x**(N-i-1) for i in range(N)]) 
print(matrix)  

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [3]:
import numpy as np

def moving_average(a, n=3):
    asum = np.cumsum(a, dtype=float)
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
a1=np.array(a) #rounding off the results to two digts 
np.array(moving_average(a1,n=3)).round(2) 

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

In [121]:
import pandas as pd
a =[]
N = int(input('Number of samples = '))              
for i in range(0,N):
    val = float(input('input sample values: '))
    a.append(val)             
print(a)






Number of samples = 5
input sample values: 2
input sample values: 3
input sample values: 4
input sample values: 5
input sample values: 5
[2.0, 3.0, 4.0, 5.0, 5.0]


In [84]:
import numpy as np
def Moving_Averages():
    
        try:
            interval = int(input('Moving Average Window= '))
            a =[]        
            N = int(input('Number of samples = '))            
            for i in range(0,N):
                val = float(input('input sample values: '))
                a.append(val)
        except:
            print("wrong value type for an input value,\nkindly input an integer for the 'Moving Average Window and Number of samples'\nThen, input either an Integer or a float for 'Sample values'\nImplication: Inaccurate result for the moving Average")
        try:    
            a= np.array(a)
            b=[]
            i=0
            j=interval
        
            while (j<=N):        
                p=(a[i:j].sum())/(j-i)        
                b.append(round(p,2))
                i = i+1
                j= j+1
            print('The {} Window Moving Average = {}'.format(interval, b) )
        except Exception as e:
            print(e)
            
            
    

In [87]:
#a =[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
#
Moving_Averages()


Moving Average Window= 3
Number of samples = 13
input sample values: 3
input sample values: 5
input sample values: 7
input sample values: 2
input sample values: 8
input sample values: 10
input sample values: 11
input sample values: 65
input sample values: 72
input sample values: 81
input sample values: 99
input sample values: 100
input sample values: 150
The 3 Window Moving Average = [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]


In [80]:
import numpy as np
a = [1,2,3,4,5]
a= np.array(a)
a.sum()

15